### ISSUE TITLE
Graceful Exit and KeyboardInterrupt

### ISSUE THREAD

**Issue by maxkr1604** [SeisSolUQ/mtmlda#5]
I have spent a couple hours finding a nice way to incorporate KeyboardInterrupt into the standard try/except handling within the MTMLDA sampler (to save the chain and print out a tree file). This is not straight forward within Treading and Multiprocessing environments. Maybe a custom signal handler would do the trick, but I haven't found a solution that works yet.
In general, it would be good to have such handling, so that the chain is not lost when we get some external SIGINT, particularly in cluster environments.

**Comment by vikaskurapati** [comment]
> Right now, I am leaning more in the direction of moving the chain saving into the MCMC loop in the form of checkpointing. Then we wouldn't have to worry about that.

sorry to bring this back again. Does this mean, if some external SIGINT is received, and the chain is saved, if I use these chains as my checkpoint loads, the next samples picked for the next MLDA run setup would be correctly picked from the previous saved files even if it is interrupted? If that is the case #7 would not be really needed  and this issue actually solves the issue, doesn't it?
